export const BEGIN_LOGIN = "BEGIN_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const BEGIN_SIGNUP = "BEGIN_SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const AUTH_SIGNUP_FAIL = "AUTH_SIGNUP_FAIL";

export const BEGIN_FIND_USER = "BEGIN_FIND_USER";
export const FIND_USER_SUCCESS = "FIND_USER_SUCCESS";
export const FIND_USER_FAIL = "FIND_USER_FAIL";

export const BEGIN_ADD_SELF_TAG = "BEGIN_ADD_SELF_TAG";
export const ADD_SELF_TAG_FAIL = "ADD_SELF_TAG_FAIL";
export const ADD_SELF_TAG_SUCCESS = "ADD_SELF_TAG_SUCCESS";